services:
    app:
        image: php:8.4-fpm
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - mongodb
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: laravel_web
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        ports:
            - "27017:27017"
        volumes:
            - ./volumes/mongo_data:/data/db
        networks:
            - laravel

networks:
    laravel:

volumes:
    mongo_data:
